import { TemplateConfig } from '@/types/template'

export const governmentTemplate: TemplateConfig = {
  id: 'tpl_gov_001',
  key: 'government',
  version: '1.0.0',
  name: '정부지원용 사업계획서',
  description: 'R&D 과제, 정부 창업지원, 기술개발 과제 신청용 사업계획서 템플릿',
  sections: [
    {
      code: 'summary',
      title: '사업 개요',
      minChars: 1800,
      maxChars: 2400,
      required: true,
    },
    {
      code: 'company_intro',
      title: '기업 소개 및 역량',
      minChars: 1500,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'technology',
      title: '기술 개발 현황 및 계획',
      minChars: 2000,
      maxChars: 2500,
      required: true,
    },
    {
      code: 'market_analysis',
      title: '시장 분석 및 전망',
      minChars: 1800,
      maxChars: 2200,
      required: true,
    },
    {
      code: 'business_model',
      title: '사업화 전략 및 모델',
      minChars: 1600,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'competitive_analysis',
      title: '경쟁 분석 및 우위성',
      minChars: 1400,
      maxChars: 1800,
      required: true,
    },
    {
      code: 'rd_plan',
      title: 'R&D 추진 계획',
      minChars: 2000,
      maxChars: 2500,
      required: true,
    },
    {
      code: 'finance_plan',
      title: '재무 계획 (5개년)',
      minChars: 1500,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'risk_management',
      title: '위험 요인 및 대응방안',
      minChars: 1200,
      maxChars: 1600,
      required: true,
    },
    {
      code: 'expected_effects',
      title: '기대 효과 및 파급력',
      minChars: 1000,
      maxChars: 1400,
      required: true,
    },
  ],
  questions: [
    {
      id: 'q1',
      label: '회사명 및 사업자등록번호',
      placeholder: '예: (주)G-Won AI, 123-45-67890',
      mapTo: 'company.name',
      type: 'short',
      required: true,
    },
    {
      id: 'q2', 
      label: '주요 개발 기술 및 제품',
      placeholder: '예: AI 기반 사업계획서 자동생성 시스템',
      mapTo: 'product.name',
      type: 'short',
      required: true,
    },
    {
      id: 'q3',
      label: '기술의 핵심 가치 및 차별점',
      placeholder: '기존 기술 대비 우수성, 독창성 등을 간단히 설명',
      mapTo: 'product.uniqueValue',
      type: 'long',
      required: true,
    },
    {
      id: 'q4',
      label: '대상 시장 및 규모',
      placeholder: '예: 국내 중소기업 대상, 연 3조원 규모',
      mapTo: 'market.size',
      type: 'short',
      required: true,
    },
    {
      id: 'q5',
      label: '주요 경쟁업체 및 경쟁 우위',
      placeholder: '경쟁사 대비 차별화 포인트를 구체적으로 기술',
      mapTo: 'market.competitors',
      type: 'long',
    },
    {
      id: 'q6',
      label: 'R&D 투자 계획 (5년간)',
      placeholder: '연도별 R&D 투자 금액 (단위: 백만원)',
      mapTo: 'finance.capex5y',
      type: 'short',
    },
    {
      id: 'q7',
      label: '매출 목표 (5개년)',
      placeholder: '2025: 5억, 2026: 15억, 2027: 30억...',
      mapTo: 'finance.sales5y',
      type: 'short',
      required: true,
    },
    {
      id: 'q8',
      label: '개발 단계 및 TRL 수준',
      placeholder: '예: 프로토타입 완료, TRL 6단계',
      mapTo: 'product.developmentStage',
      type: 'select',
      options: ['아이디어(TRL 1-2)', '기초연구(TRL 3-4)', '응용연구(TRL 5-6)', '프로토타입(TRL 7-8)', '상용화(TRL 9)'],
    },
    {
      id: 'q9',
      label: '정부지원 필요 분야',
      placeholder: '예: R&D 자금, 인력 지원, 시설·장비 등',
      mapTo: 'funding.areas',
      type: 'multi',
      options: ['R&D 자금', '인력 지원', '시설·장비', '마케팅', '해외진출', '기타'],
    },
    {
      id: 'q10',
      label: '기대되는 사회적 파급효과',
      placeholder: '일자리 창출, 산업 기여도, 국가 경쟁력 향상 등',
      mapTo: 'impact.social',
      type: 'long',
    },
  ],
}