import { TemplateConfig } from '@/types/template'

export const investmentTemplate: TemplateConfig = {
  id: 'tpl_inv_001',
  key: 'investment',
  version: '1.0.0',
  name: '투자유치용 사업계획서',
  description: 'VC, PE, 엔젤투자자 대상 투자유치용 사업계획서 템플릿',
  sections: [
    {
      code: 'executive_summary',
      title: 'Executive Summary',
      minChars: 2000,
      maxChars: 2500,
      required: true,
    },
    {
      code: 'problem_solution',
      title: '문제 정의 및 솔루션',
      minChars: 1800,
      maxChars: 2200,
      required: true,
    },
    {
      code: 'market_opportunity',
      title: '시장 기회 및 규모',
      minChars: 1800,
      maxChars: 2200,
      required: true,
    },
    {
      code: 'product_service',
      title: '제품/서비스 소개',
      minChars: 1600,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'business_model',
      title: '비즈니스 모델 및 수익구조',
      minChars: 1500,
      maxChars: 1900,
      required: true,
    },
    {
      code: 'traction_milestones',
      title: 'Traction 및 주요 성과',
      minChars: 1200,
      maxChars: 1600,
      required: true,
    },
    {
      code: 'competitive_landscape',
      title: '경쟁 환경 및 차별화',
      minChars: 1400,
      maxChars: 1800,
      required: true,
    },
    {
      code: 'financial_projections',
      title: '재무 전망 및 지표',
      minChars: 1600,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'team_organization',
      title: '팀 구성 및 조직도',
      minChars: 1000,
      maxChars: 1400,
      required: true,
    },
    {
      code: 'funding_use',
      title: '투자금 사용 계획',
      minChars: 1200,
      maxChars: 1600,
      required: true,
    },
    {
      code: 'growth_strategy',
      title: '성장 전략 및 로드맵',
      minChars: 1400,
      maxChars: 1800,
      required: true,
    },
    {
      code: 'exit_strategy',
      title: 'Exit 전략',
      minChars: 800,
      maxChars: 1200,
      required: false,
    },
  ],
  questions: [
    {
      id: 'q1',
      label: '스타트업명 및 설립일',
      placeholder: '예: (주)G-Won AI, 2024.01.15 설립',
      mapTo: 'company.name',
      type: 'short',
      required: true,
    },
    {
      id: 'q2',
      label: '해결하고자 하는 핵심 문제',
      placeholder: '타겟 고객이 겪는 주요 Pain Point를 구체적으로 설명',
      mapTo: 'problem.description',
      type: 'long',
      required: true,
    },
    {
      id: 'q3',
      label: '제품/서비스 솔루션',
      placeholder: '문제를 해결하는 핵심 솔루션과 주요 기능',
      mapTo: 'product.solution',
      type: 'long',
      required: true,
    },
    {
      id: 'q4',
      label: 'TAM/SAM/SOM 시장 규모',
      placeholder: '예: TAM 100조, SAM 10조, SOM 1조 (출처 포함)',
      mapTo: 'market.size',
      type: 'short',
      required: true,
    },
    {
      id: 'q5',
      label: '수익 모델 및 단가',
      placeholder: '예: 구독형 SaaS, 월 9만원, 거래 수수료 3%',
      mapTo: 'revenue.model',
      type: 'short',
      required: true,
    },
    {
      id: 'q6',
      label: '핵심 Traction 지표',
      placeholder: '예: MAU 50만, 월 매출 5억, 재방문율 80%',
      mapTo: 'traction.metrics',
      type: 'short',
      required: true,
    },
    {
      id: 'q7',
      label: '5개년 매출/손익 전망',
      placeholder: '2025: 10억/△2억, 2026: 50억/5억...',
      mapTo: 'finance.projections',
      type: 'short',
      required: true,
    },
    {
      id: 'q8',
      label: '창업팀 구성 및 경력',
      placeholder: 'CEO, CTO 등 핵심멤버 배경 및 보유 역량',
      mapTo: 'team.composition',
      type: 'long',
      required: true,
    },
    {
      id: 'q9',
      label: '투자 유치 규모 및 라운드',
      placeholder: '예: 시리즈 A, 50억원 목표',
      mapTo: 'funding.round',
      type: 'short',
      required: true,
    },
    {
      id: 'q10',
      label: '투자금 주요 사용처',
      placeholder: '예: 개발 40%, 마케팅 30%, 인건비 20%, 운영 10%',
      mapTo: 'funding.allocation',
      type: 'short',
      required: true,
    },
    {
      id: 'q11',
      label: '3-5년 후 예상 밸류에이션',
      placeholder: '예: IPO 목표, 기업가치 5,000억 추정',
      mapTo: 'exit.valuation',
      type: 'short',
    },
  ],
}