import { TemplateConfig } from '@/types/template'

export const loanTemplate: TemplateConfig = {
  id: 'tpl_loan_001',
  key: 'loan',
  version: '1.0.0',
  name: '대출용 사업계획서',
  description: '은행, 신용보증기금, 기술보증기금 등 금융기관 대출용 사업계획서 템플릿',
  sections: [
    {
      code: 'business_overview',
      title: '사업 개요',
      minChars: 1600,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'company_profile',
      title: '회사 현황 및 연혁',
      minChars: 1200,
      maxChars: 1600,
      required: true,
    },
    {
      code: 'management_team',
      title: '경영진 및 조직 현황',
      minChars: 1000,
      maxChars: 1400,
      required: true,
    },
    {
      code: 'business_plan',
      title: '사업 계획 및 전략',
      minChars: 1800,
      maxChars: 2200,
      required: true,
    },
    {
      code: 'market_analysis',
      title: '시장 분석 및 마케팅 계획',
      minChars: 1600,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'financial_status',
      title: '재무 현황 및 실적',
      minChars: 1400,
      maxChars: 1800,
      required: true,
    },
    {
      code: 'financial_projections',
      title: '향후 재무 계획 (3-5년)',
      minChars: 1600,
      maxChars: 2000,
      required: true,
    },
    {
      code: 'loan_purpose',
      title: '대출 목적 및 사용 계획',
      minChars: 1200,
      maxChars: 1600,
      required: true,
    },
    {
      code: 'repayment_plan',
      title: '상환 계획 및 담보',
      minChars: 1000,
      maxChars: 1400,
      required: true,
    },
    {
      code: 'risk_analysis',
      title: '리스크 분석 및 대응방안',
      minChars: 1200,
      maxChars: 1600,
      required: true,
    },
  ],
  questions: [
    {
      id: 'q1',
      label: '회사명 및 사업자등록정보',
      placeholder: '예: (주)G-Won AI, 사업자번호 123-45-67890',
      mapTo: 'company.basic',
      type: 'short',
      required: true,
    },
    {
      id: 'q2',
      label: '주요 사업 분야 및 업종',
      placeholder: '예: 소프트웨어 개발 및 공급업, AI 솔루션 제공',
      mapTo: 'company.industry',
      type: 'short',
      required: true,
    },
    {
      id: 'q3',
      label: '설립일 및 주요 연혁',
      placeholder: '설립일, 주요 사업 확장, 기술개발 이력 등',
      mapTo: 'company.history',
      type: 'long',
      required: true,
    },
    {
      id: 'q4',
      label: '임직원 수 및 핵심 인력',
      placeholder: '예: 총 25명 (개발 15명, 영업 5명, 관리 5명)',
      mapTo: 'company.employees',
      type: 'short',
      required: true,
    },
    {
      id: 'q5',
      label: '최근 3개년 매출 실적',
      placeholder: '2022: 15억, 2023: 25억, 2024: 40억(예상)',
      mapTo: 'finance.recentSales',
      type: 'short',
      required: true,
    },
    {
      id: 'q6',
      label: '향후 5년간 매출 계획',
      placeholder: '2025: 60억, 2026: 100억, 2027: 150억...',
      mapTo: 'finance.futureSales',
      type: 'short',
      required: true,
    },
    {
      id: 'q7',
      label: '대출 신청 금액 및 목적',
      placeholder: '예: 30억원, 운영자금 20억 + 시설투자 10억',
      mapTo: 'loan.purpose',
      type: 'short',
      required: true,
    },
    {
      id: 'q8',
      label: '상환 계획 (기간 및 방식)',
      placeholder: '예: 5년 만기, 원금균등분할상환, 월 상환액 약 6천만원',
      mapTo: 'loan.repayment',
      type: 'short',
      required: true,
    },
    {
      id: 'q9',
      label: '담보 및 보증 현황',
      placeholder: '부동산 담보, 신용보증기금 보증, 연대보증인 등',
      mapTo: 'loan.collateral',
      type: 'short',
      required: true,
    },
    {
      id: 'q10',
      label: '주요 거래처 및 매출 구성',
      placeholder: '예: A사 30%, B사 25%, C사 20% 등 주요 고객사',
      mapTo: 'business.customers',
      type: 'short',
      required: true,
    },
  ],
}